---

# TODO: Basic verification of the showroom service
#   - does it run, all of it?

- name: Compute port suffix when non-standard port is used
  ansible.builtin.set_fact:
    f_port_suffix: "{% if (showroom_primary_port | default(443) | int) != 443 %}:{{ showroom_primary_port }}{% endif %}"

- name: Capture lab_ui_url as fact
  ansible.builtin.set_fact:
    f_lab_ui_url: "https://{{ showroom_host }}{{ f_port_suffix | default('') }}/{{ showroom_primary_path }}"

- name: Output showroom view(s) URLs as userinfo and userdata
  agnosticd_user_info:
    msg:
      - "Your Lab URL: {{ f_lab_ui_url }}"
      - "Your Showroom URL: {{ f_lab_ui_url }}"
      - "Your Showroom Host: {{ showroom_host }}"
    data:
      lab_ui_url: "{{ f_lab_ui_url }}"
      showroom_primary_view_url: "{{ f_lab_ui_url }}"
      showroom_host: "{{ showroom_host }}"
