---
# First target is OCP with bastion
#
# if we're using the shared cluster
# .. create a kubeconfig file
# .. get the user-data.yaml
# .. create the namespace
# .. run the helm chart
#
# for a shared cluster with a serviceaccount user
# must create namespace here because
# helm chart cannot create the namespace
# because it doesn't respect ProjectRequest
#
# use _showroom_kubeconfig if showroom user was setup
# otherwise use default

- name: Prepare Variables
  ansible.builtin.include_tasks: prepare-variables.yaml

- name: Deploy using Helm
  when: ocp4_workload_showroom_deployment_type == "helm"
  block:
  - name: Check if Helm needs to be installed
    ansible.builtin.include_tasks: check-and-install-helm.yaml

  - name: Deploy showroom via Helm (single user)
    when:
    - not _showroom_user_data.users is defined
    - ocp4_workload_showroom_deployer_chart_name | default("") != "zerotouch"
    vars:
      _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}"
      _showroom_vars: "{{ _showroom_user_data | combine({'guid': guid}) }}"
    ansible.builtin.include_tasks:
      file: deploy-showroom-helm.yaml

  - name: Deploy showroom via Helm (multi user)
    when:
    - _showroom_user_data.users is defined
    - ocp4_workload_showroom_deployer_chart_name | default("") != "zerotouch"
    vars:
      _showroom_user: "{{ _showroom_users_item.key }}"
      _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}-{{ _showroom_user }}"
      _showroom_vars: "{{ _showroom_users_item.value | combine({'guid': guid, 'user': _showroom_user}) }}"
    ansible.builtin.include_tasks:
      file: deploy-showroom-helm.yaml
    loop: "{{ _showroom_user_data.users | dict2items }}"
    loop_control:
      loop_var: _showroom_users_item
      label: "{{ _showroom_users_item.key }}"

  - name: Deploy showroom via Helm (single user) (zerotouch)
    when:
    - not _showroom_user_data.users is defined
    - ocp4_workload_showroom_deployer_chart_name | default("") == "zerotouch"
    vars:
      _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}"
      _showroom_vars: "{{ _showroom_user_data | combine({'guid': guid}) }}"
    ansible.builtin.include_tasks:
      file: deploy-showroom-helm-zerotouch.yaml

  - name: Deploy showroom via Helm (multi user) (zerotouch)
    when:
    - _showroom_user_data.users is defined
    - ocp4_workload_showroom_deployer_chart_name | default("") == "zerotouch"
    vars:
      _showroom_user: "{{ _showroom_users_item.key }}"
      _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}-{{ _showroom_user }}"
      _showroom_vars: "{{ _showroom_users_item.value | combine({'guid': guid, 'user': _showroom_user}) }}"
    ansible.builtin.include_tasks:
      file: deploy-showroom-helm-zerotouch.yaml
    loop: "{{ _showroom_user_data.users | dict2items }}"
    loop_control:
      loop_var: _showroom_users_item
      label: "{{ _showroom_users_item.key }}"


- name: Report Variables to user_data (single user)
  when: not _showroom_user_data.users is defined
  vars:
    _showroom_vars: "{{ _showroom_user_data | combine({'guid': guid}) }}"
    _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}"
  ansible.builtin.include_tasks:
    file: report-variables.yaml

- name: Report Variables to user_data (multi user)
  when: _showroom_user_data.users is defined
  vars:
    _showroom_user: "{{ _showroom_users_item.key }}"
    _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}-{{ _showroom_user }}"
    _showroom_vars: "{{ _showroom_users_item.value | combine({'guid': guid, 'user': _showroom_user}) }}"
  ansible.builtin.include_tasks:
    file: report-variables.yaml
  loop: "{{ _showroom_user_data.users | dict2items }}"
  loop_control:
    loop_var: _showroom_users_item
    label: "{{ _showroom_users_item.key }}"
